apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-magiewebapp
  labels:
    app: nginx-magiewebapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-magiewebapp
  template:
    metadata:
      labels:
        app: nginx-magiewebapp  
    spec:
      containers:
        - name: deploment-container-magiewebapp
          image: moatez/magiewebapp:v1
          imagePullPolicy: Always
          ports:
          - containerPort: 80
        - image: moatez/magieapi:v1
          name: api
          ports:
          - containerPort: 5000
            name: http
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service-label-key: service-magiewebapp-value 
  name: service-magiewebapp-clusterip
spec:
  type: ClusterIP
  ports:
  - name: service-port-name
    port: 80
    protocol: TCP
  selector:
    app: nginx-magiewebapp
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service-label-key: service-magiewebapp-value 
  name: service-magiewebapp-loadbalancer
spec:
  type: LoadBalancer
  ports:
  - name: service-port-name
    port: 80
    protocol: TCP
  - name: service-port-api
    port: 5000
    protocol: TCP
  selector:
    app: nginx-magiewebapp
