apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    label: backends
  name: email-services
spec:
  replicas: 2
  selector:
    matchLabels:
      label: backends
  template:
    metadata:
      labels:
        label: backends
    spec:
      containers:
      - image: moatez/magieapi:v5
        name: email-services
        ports:
        - containerPort: 8080
        volumeMounts:
          - mountPath: "/logsEmails"
            name: task-pv-storage-api
      volumes:
        - name: task-pv-storage-api
          persistentVolumeClaim:
            claimName: task-pv-claim-api
