apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - image: moatez/magieapi:v1
          name: api
          ports:
          - containerPort: 5000
            name: http
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service-label-key: service-api-value 
  name: service-api-clusterip
spec:
  type: ClusterIP
  ports:
  - name: service-port-name
    port: 5000
    protocol: TCP
  selector:
    app: api
