apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-name
  labels:
    app: nginx-magiewebapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-magiewebapp
  template:
    metadata:
      labels:
        app: nginx-magiewebapp  
    spec:
      containers:
        - name: deploment-container-name
          image: moatez/magiewebapp:v1
          imagePullPolicy: Always
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service-label-key: service-label-value 
  name: service-name
spec:
  type: ClusterIP
  ports:
  - name: service-port-name
    port: 80
    protocol: TCP
  selector:
    app: nginx-magiewebapp
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service-label-key: service-label-value 
  name: service-name-loadbalancer
spec:
  type: LoadBalancer
  ports:
  - name: service-port-name
    port: 80
    protocol: TCP
  selector:
    app: nginx-magiewebapp