apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim-api
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
